In [2]:
# Ejercicio 4
# Estudiante: GABRIEL ALEXANDER ANDRADE BELTRÁN

import numpy as np
import sympy as sp

print("Resolución del ejercicio 4:")
print("Operaciones con matrices:")
A = np.array([[1, 2, 0],
              [0, 1, 1],
              [3, 0, 2]])

B = np.array([[2, 1, 1],
              [1, 0, 3],
              [0, 2, 1]])

# Cálculo del producto matricial
producto_matricial = np.dot(A, B)
print("A × B =")
print(producto_matricial)

# Cálculo de la transpuesta de B
transpuesta_B = B.T
print("\nTranspuesta de B =")
print(transpuesta_B)

# Cálculo del determinante de A
determinante_A = np.linalg.det(A)
print(f"\nDeterminante de A = {determinante_A:.2f}")

# Prueba para la inversa de A y cálculo
try:
    inversa_A = np.linalg.inv(A)
    print("Inversa de A =")
    print(inversa_A)
except np.linalg.LinAlgError:
    print("La matriz A no tiene inversa.")

# Operaciones con vectores
print("\nOperaciones con vectores:")
u = np.array([1, -2, 3])
v = np.array([0, 1, 4])

# Producto punto
producto_punto = np.dot(u, v)
print(f"u · v = {producto_punto}")

# Magnitudes de los vectores
magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)
print(f"|u| = {magnitud_u:.4f}")
print(f"|v| = {magnitud_v:.4f}")

# Cálculo del ángulo entre los vectores
# cos(θ) = (u·v) / (|u|·|v|)
if magnitud_u > 0 and magnitud_v > 0:
    cos_theta = producto_punto / (magnitud_u * magnitud_v)
    cos_theta = np.clip(cos_theta, -1, 1)
    angulo_rad = np.arccos(cos_theta)
    angulo_grad = np.degrees(angulo_rad)
    print(f"Ángulo entre u y v = {angulo_grad:.2f}°")
else:
    print("No se puede calcular el ángulo.")

# Derivadas
print("\nCálculo de las derivadas:")
x = sp.Symbol('x')
f = x**4 - 3*x**3 + 2*x - 5

# Primera y segunda derivada
primera_derivada = sp.diff(f, x)
segunda_derivada = sp.diff(f, x, 2)

print(f"f(x) = {f}")
print(f"f'(x) = {primera_derivada}")
print(f"f''(x) = {segunda_derivada}")

# Evaluando las derivadas con el valor de 2
x_valor = 2
f_prima_valor = primera_derivada.subs(x, x_valor)
f_segunda_valor = segunda_derivada.subs(x, x_valor)

print(f"\nEvaluación en x = {x_valor}:")
print(f"f'({x_valor}) = {f_prima_valor}")
print(f"f''({x_valor}) = {f_segunda_valor}")

# Análisis de concavidad
if f_segunda_valor > 0:
    concavidad = "Cóncava hacia arriba"
elif f_segunda_valor < 0:
    concavidad = "Cóncava hacia abajo"
else:
    concavidad = "Punto de inflexión"

print(f"\nConcavidad en x = {x_valor}:")
print(f"f''({x_valor}) = {f_segunda_valor} → {concavidad}")

Resolución del ejercicio 4:
Operaciones con matrices:
A × B =
[[4 1 7]
 [1 2 4]
 [6 7 5]]

Transpuesta de B =
[[2 1 0]
 [1 0 2]
 [1 3 1]]

Determinante de A = 8.00
Inversa de A =
[[ 0.25  -0.5    0.25 ]
 [ 0.375  0.25  -0.125]
 [-0.375  0.75   0.125]]

Operaciones con vectores:
u · v = 10
|u| = 3.7417
|v| = 4.1231
Ángulo entre u y v = 49.59°

Cálculo de las derivadas:
f(x) = x**4 - 3*x**3 + 2*x - 5
f'(x) = 4*x**3 - 9*x**2 + 2
f''(x) = 6*x*(2*x - 3)

Evaluación en x = 2:
f'(2) = -2
f''(2) = 12

Concavidad en x = 2:
f''(2) = 12 → Cóncava hacia arriba
