
## Ejercicio 3

Nombre del estudiante: Brayan Maisincho

**Matrices:**  
A = [[2, 1], [0, 3]]  
B = [[1, 2], [3, 0]]  

1. Calcula A + B y A × B.  
2. Calcula la inversa de A y el determinante de B.

**Vectores:**  
u = [1, 3]  
v = [-1, 2]  

1. Calcula el producto interno u·v.  
2. Calcula la magnitud de cada vector.

**Derivadas:**  
h(x) = sin(2*x**2 + 3*x)  

1. Calcula la derivada h'(x) usando regla de la cadena.  
2. Evalúa h'(1) y h'(0).

In [3]:
import numpy as np
import sympy as sp

# Matrices 

print("Operaciones con Matrices")

A = np.array([[2, 1],
              [0, 3]])

B = np.array([[1, 2],
              [3, 0]])

# suma (A + B)
suma_matrices = A + B
print(f"Suma de A + B:\n{suma_matrices}\n")

# producto matricial (A × B)
producto_matrices = A @ B
print(f"Producto de A × B:\n{producto_matrices}\n")

producto_con_dot = np.dot(A, B)
print(f"Resultado usando np.dot(A, B):\n{producto_con_dot}\n")

# inversa de A
inversa_A = np.linalg.inv(A)
print(f"Inversa de A:\n{inversa_A}\n")

# determinante de B
determinante_B = np.linalg.det(B)
print(f"Determinante de B:\n{determinante_B}\n")


# Vectores

print("\nOperaciones con Vectores")

u = np.array([1, 3])
v = np.array([-1, 2])

producto_interno = np.dot(u, v)
print(f"Producto interno u·v: {producto_interno}\n")

# magnitud de cada vector
magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)
print(f"Magnitud del vector u: {magnitud_u}")
print(f"Magnitud del vector v: {magnitud_v}\n")


# Derivadas

print("\nCálculo de Derivadas")

x = sp.symbols('x')

h_x = sp.sin(2*x**2 + 3*x)
print(f"Función original h(x) = {h_x}\n")

# derivada de h(x) con respecto a x
# regla de la cadena
h_prima_x = sp.diff(h_x, x)
print(f"Derivada h'(x) = {h_prima_x}\n")

# x = 1 y x = 0
valor_h_prima_1 = h_prima_x.subs(x, 1).evalf() #decimal
valor_h_prima_0 = h_prima_x.subs(x, 0).evalf()

print(f"Valor de h'(1): {valor_h_prima_1}")
print(f"Valor de h'(0): {valor_h_prima_0}")

Operaciones con Matrices
Suma de A + B:
[[3 3]
 [3 3]]

Producto de A × B:
[[5 4]
 [9 0]]

Resultado usando np.dot(A, B):
[[5 4]
 [9 0]]

Inversa de A:
[[ 0.5        -0.16666667]
 [ 0.          0.33333333]]

Determinante de B:
-6.0


Operaciones con Vectores
Producto interno u·v: 5

Magnitud del vector u: 3.1622776601683795
Magnitud del vector v: 2.23606797749979


Cálculo de Derivadas
Función original h(x) = sin(2*x**2 + 3*x)

Derivada h'(x) = (4*x + 3)*cos(2*x**2 + 3*x)

Valor de h'(1): 1.98563529824258
Valor de h'(0): 3.00000000000000
