In [ ]:
"""
Ejercicio 2
Realizado por: Joseph Carrera
"""
import numpy as np
import sympy as sp
# Matrices
A = np.array([[1,0,2],[2,1,1],[3,2,0]])
B = np.array([[0,1,1],[1,2,0],[2,1,3]])

multiplicacion_matrices = np.dot(A,B)
transpuesta_A = A.T
determinante_A = np.linalg.det(A)

print("A X B =\n", multiplicacion_matrices)
print("Transpuesta A =\n", transpuesta_A)
print("Determinante de A =",determinante_A)

A X B =
 [[4 3 7]
 [3 5 5]
 [2 7 3]]
Transpuesta A =
 [[1 2 3]
 [0 1 2]
 [2 1 0]]
Determinante de A = -4.440892098500646e-16


In [ ]:
#Vectores
u = np.array([2,-1,3])
v = np.array([1,4,-2])

producto_escalar = np.dot(u,v)

if producto_escalar == 0:
    print(f"Los vectores u={u} y v={v} son ortoganales")
else:
    print(f"Los vectores u={u} y v={v} no son ortoganales")

normal_u = np.linalg.norm(u)
normal_v = np.linalg.norm(v)
angulo_radianes = np.arccos(producto_escalar / (normal_u * normal_v))
angulo_grados = np.degrees(angulo_radianes)

print(f"Entre los vectores u y v exiten {angulo_grados:.2f}°")

Los vectores u=[ 2 -1  3] y v=[ 1  4 -2] no son ortoganales
Entre los vectores u y v exiten 117.81°


In [6]:
#Derivadas
x,y = sp.symbols('x,y')
g = x*2*y + sp.sin(x*y)

dg_dx = sp.diff(g,x)
dg_dy = sp.diff(g,y)

print("g(x,y) = ",g)
print("ag/ax = ", dg_dx)
print("ag/ay = ", dg_dy)

evluado_g = g.subs({x: 1, y: sp.pi/2})
evaluado_dg_dx = dg_dx.subs({x: 1, y: sp.pi/2})
evaluado_dg_dy = dg_dy.subs({x: 1, y: sp.pi/2})

print(f"\npunto = (1,pi/2)")
print("g(punto) = ",evluado_g)
print("dg/dx(punto) = ",evaluado_dg_dx)
print("dg/dy(punto) = ",evaluado_dg_dy)

g(x,y) =  2*x*y + sin(x*y)
ag/ax =  y*cos(x*y) + 2*y
ag/ay =  x*cos(x*y) + 2*x

punto = (1,pi/2)
g(punto) =  1 + pi
dg/dx(punto) =  pi
dg/dy(punto) =  2
