In [6]:
import numpy as np
import sympy as sp

# Mactrices
A = np.array([[2, 1], [0, 3]])  
B = np.array([[1, 2], [3, 0]])  
#Suma A + B
C = A + B
print("A + B =\n", C)
#Producto A * B
D = A @ B
print("A * B =\n", D)

# Inversa de A
inversaA = np.linalg.inv(A)
print("Inversa de A =\n", inversaA)

# Determinante de B
detB = np.linalg.det(B)
print("Determinante de B =\n", detB)

# Vectores

u = np.array([1, 3])  
v = np.array([-1, 2])  
# Producto interno u·v
producto_interno = u @ v
print("Producto interno u·v =", producto_interno)

# Magnitud de cada vector
magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)
print("Magnitud de u =", magnitud_u)
print("Magnitud de v =", magnitud_v)

# Derivadas
# h(x) = sin(2*x**2 + 3*x)  
x = sp.symbols('x')
h = sp.sin(2*x**2 + 3*x)

# Derivada h'(x) uando regla de la cadena
h_derivada = sp.diff(h, x)

# Evaluar h'(1) y h'(0)
h_derivada_eval_1 = h_derivada.subs(x, 1)
h_derivada_eval_0 = h_derivada.subs(x, 0)


A + B =
 [[3 3]
 [3 3]]
A * B =
 [[5 4]
 [9 0]]
Inversa de A =
 [[ 0.5        -0.16666667]
 [ 0.          0.33333333]]
Determinante de B =
 -6.0
Producto interno u·v = 5
Magnitud de u = 3.1622776601683795
Magnitud de v = 2.23606797749979
