# ----------------------------------------------------------
# EJERCICIO 2
# ----------------------------------------------------------
"""
## Ejercicio 2

**Matrices:**  
A = [[1, 0, 2], [2, 1, 1], [3, 2, 0]]  
B = [[0, 1, 1], [1, 2, 0], [2, 1, 3]]  

1. Calcula A × B.  
2. Calcula la traspuesta y determinante de A.

**Vectores:**  
u = [2, -1, 3]  
v = [1, 4, -2]  

1. Calcula el producto interno u·v y determina si son ortogonales.  
2. Calcula el ángulo entre u y v.

**Derivadas:**  
g(x, y) = x**2 * y + sin(x*y)  

1. Calcula las derivadas parciales ∂g/∂x y ∂g/∂y.  
2. Evalúa en el punto (x=1, y=π/2).
"""

# Nombre del estudiante:
# Nombre: Jaime Andrés Estrada

In [7]:
# Matrices
import numpy as np

A = np.array([[1, 0, 2],
              [2, 1, 1],
              [3, 2, 0]])  

B = np.array([[0, 1, 1],
              [1, 2, 0],
              [2, 1, 3]])

print("Matriz A: \n", A)
print("\n" + "=" * 100)
print("Matriz B: \n", B)
print("\n" + "=" * 100)

# 1. Calculo AxB
print("A x B = \n", np.dot(A, B))

# 2. Calculo transpuesta y determinante
print("\nTranspuesta de A: \n", A.T)
determinante_A = np.linalg.det(A)
print(f"Determinante de A: {determinante_A:.20f}")
print("\n" + "=" * 100)
print("Transpuesta de B: \n", B.T)
determinante_B = np.linalg.det(B)
print("Determinante de B:", determinante_B)

Matriz A: 
 [[1 0 2]
 [2 1 1]
 [3 2 0]]

Matriz B: 
 [[0 1 1]
 [1 2 0]
 [2 1 3]]

A x B = 
 [[4 3 7]
 [3 5 5]
 [2 7 3]]

Transpuesta de A: 
 [[1 2 3]
 [0 1 2]
 [2 1 0]]
Determinante de A: -0.00000000000000044409

Transpuesta de B: 
 [[0 1 2]
 [1 2 1]
 [1 0 3]]
Determinante de B: -6.0


In [8]:
# Vectores
u = np.array([2, -1, 3])  
v = np.array([1, 4, -2])  

# 1. Calcula el producto interno u·v y determina si son ortogonales.
producto_interno = np.dot(u, v)
print("Producto interno:", producto_interno)

if producto_interno == 0:
    print("Los vectores son ortogonales")
else:
    print("Los vectores no son ortogonales")

# 2. Calcula el ángulo entre u y v.
norma_u = np.linalg.norm(u)
norma_v = np.linalg.norm(v)

cos_theta = producto_interno / (norma_u * norma_v)

# El valor debe estar en el rango [-1, 1] para evitar errores numéricos
cos_theta = np.clip(cos_theta, -1, 1)

angulo_radianes = np.arccos(cos_theta)
angulo_grados = np.degrees(angulo_radianes)

print(f"Ángulo entre u y v: {angulo_radianes:.4f} radianes ({angulo_grados:.2f}°)")

Producto interno: -8
Los vectores no son ortogonales
Ángulo entre u y v: 2.0562 radianes (117.81°)


In [11]:
# Derivadas
import sympy as sp

# variables simbolcias
x, y = sp.symbols('x y')

# derivada parcial
g = x**2 * y + sp.sin(x*y)

# 1. Calcula las derivadas parciales ∂g/∂x y ∂g/∂y.  
dg_dx = sp.diff(g, x)
dg_dy = sp.diff(g, y)

print("g(x, y) = ", g)
print("dg/dx = ", dg_dx)
print("dg/dy = ", dg_dy)

#2. Evalúa en el punto (x=1, y=π/2).
punto = {x: 1, y: sp.pi/2}
dg_dx_val = dg_dx.evalf(subs=punto)
dg_dy_val = dg_dy.evalf(subs=punto)

print(f"\nEn el punto (x=1, y=π/2):")
print("dg/dx =", dg_dx_val)
print("dg/dy =", dg_dy_val)

g(x, y) =  x**2*y + sin(x*y)
dg/dx =  2*x*y + y*cos(x*y)
dg/dy =  x**2 + x*cos(x*y)

En el punto (x=1, y=π/2):
dg/dx = 3.14159265358979
dg/dy = 1.00000000000000
