In [12]:
import numpy as np
import math
import sympy as sp

#======================== EJERCICIO 1 ===========================

#---------MATRICES Y OPERACIONES MATRICIALES-----------

#Definimos las matrices
A = np.array([[1,2],[3,4]])
B = np.array([[2,0],[1,2]])

# 1. Calcula A + B, A - B y el producto matricial A × B.

    # A + B
suma = A + B
print("Suma de A y B:\n", suma)
print("\n")

    # A - B
resta = A - B
print("Resta de A y B:\n", resta)
print("\n")

    # A × B
producto = np.dot(A, B)
print("Producto matricial de A y B:\n", producto)
print("\n")


# 2. Calcula la traspuesta de A y la inversa de B (si existe).

    # Transpuesta de A
transpuesta_A = np.transpose(A)
print("La transpuesta de A:\n", transpuesta_A)
print("\n")

    # Inversa de B

#Determinante
determinante_B= np.linalg.det(B)
print("Determinante de B:", determinante_B)
print("\n")

if determinante_B !=0:
    inversa_B= np.linalg.inv(B)
    print("Inversa de B:\n", inversa_B)
else:
    print("La matriz B no es invertible")


Suma de A y B:
 [[3 2]
 [4 6]]


Resta de A y B:
 [[-1  2]
 [ 2  2]]


Producto matricial de A y B:
 [[ 4  4]
 [10  8]]


La transpuesta de A:
 [[1 3]
 [2 4]]


Determinante de B: 4.0


Inversa de B:
 [[ 0.5   0.  ]
 [-0.25  0.5 ]]


In [11]:
#---------VECTORES Y OPERACIONES CON VECTORES-----------

# Definimos los vectores 
u = np.array([1, 2])
v = np.array([3, -1])

# 1. Calcula el producto interno u.v
producto_interno = np.dot(u, v)
print("Producto interno u.v:", producto_interno)

# 2.Calcula la magnitud de los vectores u y v
magnitud_u = np.linalg.norm(u)
print("Magnitud de u:", magnitud_u)
magnitud_v = np.linalg.norm(v)
print("Magnitud de v:", magnitud_v)


Producto interno u.v: 1
Magnitud de u: 2.23606797749979
Magnitud de v: 3.1622776601683795


In [14]:
#---------DERIVADAS DE PRIMER Y SEGUNDO ORDEN-----------

#Definimos la función f(x) = x**3 + 2*x**2 + x 

x = sp.symbols('x')
funcion= x**3 + 2*x**2 + x 

# 1. Calcula la derivada primera y segunda de f(x)

    # Primera derivada
d1= sp.diff(funcion, x)
print("Primera derivada f'(x):", d1)

    # Segunda derivada
d2= sp.diff(d1, x)
print("Segunda derivada f''(x):", d2)


# 2. Evalúa ambas derivadas en x = 1

eval_d1= d1.subs(x, 1)
print("Evaluación de la primera derivada en x=1:", eval_d1)

eval_d2= d2.subs(x, 1)
print("Evaluación de la segunda derivada en x=1:", eval_d2)



Primera derivada f'(x): 3*x**2 + 4*x + 1
Segunda derivada f''(x): 6*x + 4
Evaluación de la primera derivada en x=1: 8
Evaluación de la segunda derivada en x=1: 10
