# ----------------------------------------------------------
# EJERCICIO 4
# ----------------------------------------------------------
"""
## Ejercicio 4

**Matrices:**  
A = [[1, 2, 0], [0, 1, 1], [3, 0, 2]]  
B = [[2, 1, 1], [1, 0, 3], [0, 2, 1]]  

1. Calcula A × B y la traspuesta de B.  
2. Calcula el determinante de A y, si existe, su inversa.

**Vectores:**  
u = [1, -2, 3]  
v = [0, 1, 4]  

1. Calcula el producto interno u·v.  
2. Calcula la magnitud y el ángulo entre los vectores.

**Derivadas:**  
f(x) = x**4 - 3*x**3 + 2*x - 5  

1. Calcula f'(x) y f''(x).  
2. Evalúa en x = 2 y comenta la concavidad.
"""

---

**Matrices:**

In [22]:
import numpy as np
A = np.array([
            [1, 2, 0],
            [0, 1, 1],
            [3, 0, 2]
            ])  
B = np.array([
            [2, 1, 1],
            [1, 0, 3],
            [0, 2, 1]
            ])

1. Calcula A × B y la traspuesta de B.  

In [21]:
aB = np.dot(A, B)
print("Matriz A: ")
print(A)
print("\nMatriz B:")
print(B)
print("\nMatriz A x B")
print(aB)
print("\nTranspuesta de B")
print(B.T)

Matriz A: 
[[1 2 0]
 [0 1 1]
 [3 0 2]]

Matriz B:
[[2 1 1]
 [1 0 3]
 [0 2 1]]

Matriz A x B
[[4 1 7]
 [1 2 4]
 [6 7 5]]

Transpuesta de B
[[2 1 0]
 [1 0 2]
 [1 3 1]]


2. Calcula el determinante de A y, si existe, su inversa.

In [37]:
det = np.linalg.det(A)
print(f"Determinante de A {det if det is not None else None}")
inversa = np.linalg.inv(A)
print("\n Inversa de A:")
print(inversa if inversa is not None else None)

Determinante de A 7.999999999999998

 Inversa de A:
[[ 0.25  -0.5    0.25 ]
 [ 0.375  0.25  -0.125]
 [-0.375  0.75   0.125]]


---

**Vectores:**

In [11]:
u = np.array([1, -2, 3])
v = np.array([0, 1, 4])  

1. Calcula el producto interno u·v.  

In [39]:
uV = np.dot(u, v)
print(f"Vector u: {u}")
print(f"\nVector v: {u}")
print(f"\nVector u x v: {uV}")

Vector u: [ 1 -2  3]

Vector v: [ 1 -2  3]

Vector u x v: 10


2. Calcula la magnitud y el ángulo entre los vectores.

In [47]:
magU = np.linalg.norm(u)
print(f"‖v‖ = {magU:.2f}")
magV = np.linalg.norm(v)
print(f"‖u‖ = {magV:.2f}")

anguloRad = np.arccos(uV / (magU * magV))
anguloDeg = np.degrees(anguloRad)
print(f"Ángulo entre a y b = {anguloDeg:.2f}°")


‖v‖ = 3.74
‖u‖ = 4.12
Ángulo entre a y b = 49.59°


---

**Derivadas:**

In [34]:
import sympy as sp

x = sp.Symbol('x')
f = x**4 - 3*x**3 + 2*x - 5

1. Calcula f'(x) y f''(x).  

In [35]:
first = sp.diff(f, x)
print(f"f'(x) = {first}")

second = sp.diff(first, x)
print(f"f''(x) = {second}")

f'(x) = 4*x**3 - 9*x**2 + 2
f''(x) = 12*x**2 - 18*x


2. Evalúa en x = 2 y comenta la concavidad.

In [36]:
xVal = 2
firstVal = first.subs(x, xVal)
secondVal = second.subs(x, xVal)


print(f"f'(2) = {firstVal}")
print(f"f''(2) = {secondVal}")

if secondVal > 0:
    concavidad = "cóncava hacia arriba"
elif secondVal < 0:
    concavidad = "cóncava hacia abajo"
else:
    concavidad = "punto de inflexión"

print(f"Concavidad en x=2: {concavidad}")

f'(2) = -2
f''(2) = 12
Concavidad en x=2: cóncava hacia arriba
