## Ejercicio 2

**Matrices:**  
A = [[1, 0, 2], [2, 1, 1], [3, 2, 0]]  
B = [[0, 1, 1], [1, 2, 0], [2, 1, 3]]  

1. Calcula A × B.  
2. Calcula la traspuesta y determinante de A.

**Vectores:**  
u = [2, -1, 3]  
v = [1, 4, -2]  

1. Calcula el producto interno u·v y determina si son ortogonales.  
2. Calcula el ángulo entre u y v.

**Derivadas:**  
g(x, y) = x**2 * y + sin(x*y)  

1. Calcula las derivadas parciales ∂g/∂x y ∂g/∂y.  
2. Evalúa en el punto (x=1, y=π/2).

In [42]:
import numpy as np

In [46]:
# Matrices

A = np.array([[1, 0, 2], [2, 1, 1], [3, 2, 0]])
B = np.array([[0, 1, 1], [1, 2, 0], [2, 1, 3]])

print("\n--- Matrices ---")
print("Matriz A: \n", A)
print("Matriz B: \n", B)

# 1. Multiplicación de matrices A × B
print("\nA x B = \n", np.dot(A, B))

# 2. Traspuesta de A
print("\nTraspuesta de A:\n", A.T)

# Determinante de A
# El determinante es un escalar que indica propiedades de la matriz:
# - Si det(A) = 0, la matriz es singular (no tiene inversa)
# - Si det(A) ≠ 0, la matriz es invertible
determinante_A = np.linalg.det(A) 

print("\nDeterminante de A:", determinante_A)


--- Matrices ---
Matriz A: 
 [[1 0 2]
 [2 1 1]
 [3 2 0]]
Matriz B: 
 [[0 1 1]
 [1 2 0]
 [2 1 3]]

A x B = 
 [[4 3 7]
 [3 5 5]
 [2 7 3]]

Traspuesta de A:
 [[1 2 3]
 [0 1 2]
 [2 1 0]]

Determinante de A: -4.440892098500646e-16


In [44]:
# Vectores
# Definimos los vectores u y v como arrays de NumPy
u = np.array([2, -1, 3])
v = np.array([1, 4, -2])

print("\n--- Vectores ---")
print("u =", u)
print("v =", v)

# Producto interno
producto_interno = np.dot(u, v)
print("\nProducto interno (u·v) =", producto_interno)

# Dos vectores son ortogonales (perpendiculares) si su producto interno es 0
if producto_interno == 0:
    print("Los vectores son ortogonales (perpendiculares)")
else:
    print("Los vectores NO son ortogonales")

# Ángulo entre u y v
# Calculamos las normas (magnitudes) de los vectores
norma_u = np.linalg.norm(u)
norma_v = np.linalg.norm(v)

print(f"\nMagintud de u: {norma_u.round(3)}")
print(f"Magnitud de v: {norma_v.round(3)}")


# Coseno del ángulo
cos_theta = producto_interno / (norma_u * norma_v)

# Calcular el ángulo en radianes
angulo_rad = np.arccos(cos_theta)

# Convertir el ángulo a grados
angulo_grados = np.degrees(angulo_rad)

print(f"\nCoseno del ángulo: {cos_theta}")
print(f"Ángulo en radianes: {angulo_rad.round(3)}")
print(f"Ángulo en grados: {angulo_grados.round(2)}°")


--- Vectores ---
u = [ 2 -1  3]
v = [ 1  4 -2]

Producto interno (u·v) = -8
Los vectores NO son ortogonales

Magintud de u: 3.742
Magnitud de v: 4.583

Coseno del ángulo: -0.4665694748158435
Ángulo en radianes: 2.056
Ángulo en grados: 117.81°


In [47]:
# Derivadas
import sympy as sp

print("\n--- Derivadas ---")

# Variables simbólicas
x, y = sp.symbols('x y')

# función g(x, y) = x²y + sin(xy)
g = x**2 * y + sp.sin(x * y)


# derivadas parciales
# derivada de g con respecto a x(∂g/∂x)
dg_dx = sp.diff(g, x)  

# derivada de g con respecto a y(∂g/∂y)
dg_dy = sp.diff(g, y)

print(f"Función g(x, y) = {g}")
print(f"∂g/∂x = {dg_dx}")
print(f"∂g/∂y = {dg_dy}")

# evaluar las derivadas en el punto (x = 1, y = π/2)
punto = { x:1, y: sp.pi / 2 }

# sustituir los valores en las derivadas
dg_dx_eval = dg_dx.subs(punto)
dg_dy_eval = dg_dy.subs(punto)

print("\nEvaluando en el punto (x = 1, y = π/2)")
print(f"∂g/∂x = {dg_dx_eval}")
print(f"∂g/∂y = {dg_dy_eval}")


--- Derivadas ---
Función g(x, y) = x**2*y + sin(x*y)
∂g/∂x = 2*x*y + y*cos(x*y)
∂g/∂y = x**2 + x*cos(x*y)

Evaluando en el punto (x = 1, y = π/2)
∂g/∂x = pi
∂g/∂y = 1
