## Ejercicio 1

**Matrices:**  
A = [[1, 2], [3, 4]]  
B = [[2, 0], [1, 2]]  

1. Calcula A + B, A - B y el producto matricial A × B.  
2. Calcula la traspuesta de A y la inversa de B (si existe).

**Vectores:**  
u = [1, 2]  
v = [3, -1]  

1. Calcula el producto interno u·v.  
2. Calcula la magnitud de cada vector.  

**Derivadas:**  
f(x) = x**3 + 2*x**2 + x  

1. Calcula la derivada primera y segunda de f(x).  
2. Evalúa ambas derivadas en x = 1.

In [1]:
import numpy as np
import sympy as sp

In [ ]:
# Matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
print ("Matrix A:\n", A)
print ("Matrix B:\n", B)

# Operaciones con matrices
C= A + B  # Suma
D= A - B # Resta
E= np.matmul(A, B)  # producto matricial
print ("A + B :\n", C)
print ("A - B :\n", D)
print ("A X B :\n", E)

# Traspuesta
A_T = A.T
print ("Transpuesta de A:\n", A_T)

# Inversa
det_B = np.linalg.det(B)
B_inv = None
if abs(det_B) > 1e-12:
    B_inv = np.linalg.inv(B)

print("Determinante de B:", det_B)
if B_inv is not None:
    print("Inversa de B:\n", B_inv)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[2 0]
 [1 2]]
A + B :
 [[3 2]
 [4 6]]
A - B :
 [[-1  2]
 [ 2  2]]
A X B :
 [[ 4  4]
 [10  8]]
Transpuesta de A:
 [[1 3]
 [2 4]]
Inversa de B:
 [[ 0.5   0.  ]
 [-0.25  0.5 ]]


In [ ]:
# Vectores
u = np.array([1, 2])
v = np.array([3, -1])

# Producto punto
dot_uv = np.dot(u, v)
print("Producto punto u . v:", dot_uv)

# Magnitud
mag_u = np.linalg.norm(u)
mag_v = np.linalg.norm(v)
print("Magnitud de u:", mag_u)
print("Magnitud de v:", mag_v)

Producto punto u . v: 1
Magnitud de u: 2.23606797749979
Magnitud de v: 3.1622776601683795


In [9]:
# Derivadas
x = sp.symbols('x')
f = x**3 + 2*x**2 + x 
df_1 = sp.diff(f, x)  # Primera derivada
df_2 = sp.diff(f, x, 2)  # Segunda derivada
print("Función f(x):", f)
print("Primera derivada f'(x):", df_1)
print("Segunda derivada f''(x):", df_2)

# Evaluación de derivadas en un punto
punto = 1
df_1_eval = df_1.subs(x, punto)
df_2_eval = df_2.subs(x, punto)
print(f"f'({punto}) =", df_1_eval)
print(f"f''({punto}) =", df_2_eval)

Función f(x): x**3 + 2*x**2 + x
Primera derivada f'(x): 3*x**2 + 4*x + 1
Segunda derivada f''(x): 2*(3*x + 2)
f'(1) = 8
f''(1) = 10
