In [ ]:
#Ejercicio 4 actividad tutoria 18/10/2025
import numpy as np

#Matrices
A = np.array([[1,2,0],[0,1,1],[3,0,2]])
B = np.array([[2,1,1],[1,0,3],[0,2,1]])

#1. Multiplicacion de matrices y transpuesta de B

print("Multiplicacion de A x B:\n", np.dot(A,B))
print("Transpuesta de B:\n", B.T)

#2. Determinante de A y si exsite su inversa
print("Determinante de A:", np.linalg.det(A))
if np.linalg.det(A) != 0:
    print("La inversa de A es:\n", np.linalg.inv(A))
else:
    print("La matriz A no tiene inversa.")

Multiplicacion de A x B:
 [[4 1 7]
 [1 2 4]
 [6 7 5]]
Transpuesta de B:
 [[2 1 0]
 [1 0 2]
 [1 3 1]]
Determinante de A: 7.999999999999998
La inversa de A es:
 [[ 0.25  -0.5    0.25 ]
 [ 0.375  0.25  -0.125]
 [-0.375  0.75   0.125]]


In [8]:
#Vectores

u = np.array([1,-2,3])
v = np.array([0,1,4])

#1. Producto interno
print("Prodcuto interno u.v = ", np.dot(u,v))

#2. Magnitud y angulo entre vectores
magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)

print(f"La magnitud de u es: {(magnitud_u):.2f}")
print(f"La magnitud de v es: {(magnitud_v):.2f}")

#Angulo entre vectores
cos_alfa = np.dot(u,v)/(magnitud_u * magnitud_v)
alfa = np.arccos(cos_alfa)
print(f"El angulo entre el vector u y el vector v es: {np.degrees(alfa):.2f} grados")

Prodcuto interno u.v =  10
La magnitud de u es: 3.74
La magnitud de v es: 4.12
El angulo entre el vector u y el vector v es: 49.59 grados


In [22]:
#Derivadas
import sympy as sp

#f(x) =x^4 - 3*x^3 + 2*x - 5

#Primera y segunda derivada
x = sp.symbols('x')
f = x**4 + 3*x**3 + 2*x - 5

df = sp.diff(f, x)
print("F(x) = ", f)
print("\ndf/dx = ",df)

d2f = sp.diff(f,x,2)
print("d^2f/dx^2 = ", d2f)

#Evaular en x=2 y comentar la concavidad
x_value = 2
df_2 = df.subs(x, x_value)
d2f_2 = d2f.subs(x, x_value)
print(f"\nCuando x={x_value}, df/dx = {df_2}, d^2f/dx^2 = {d2f_2}\n")

#Concavidad (curvatura)

if d2f_2 > 0:
    print("La función es cóncava hacia arriba")
elif d2f_2 < 0:
    print("La función es cóncava hacia abajo")
else:
    print("Es un punto de inflexión")

F(x) =  x**4 + 3*x**3 + 2*x - 5

df/dx =  4*x**3 + 9*x**2 + 2
d^2f/dx^2 =  6*x*(2*x + 3)

Cuando x=2, df/dx = 70, d^2f/dx^2 = 84

La función es cóncava hacia arriba
