"""
# Práctica de Python – Ejercicios Combinados

📌 Instrucciones generales:

1. Cada estudiante debe elegir **uno** de los siguientes cinco ejercicios para resolver.  
2. No más de **11 estudiantes por ejercicio**.  
3. Deben escribir su **nombre completo** en la sección indicada debajo del ejercicio elegido.  
4. Todos los ejercicios se resuelven usando Python (NumPy y SymPy).  
5. Cada ejercicio incluye:
   - Operaciones con matrices
   - Operaciones con vectores
   - Derivadas (normales, parciales, de funciones compuestas o sigmoide)
"""
# ----------------------------------------------------------
# EJERCICIO 5
# ----------------------------------------------------------
"""
## Ejercicio 5

**Matrices:**  
A = [[1, 1], [2, 3]]  
B = [[0, 2], [1, 1]]  

1. Calcula A + B, A - B y A × B.  
2. Calcula la traspuesta de A y la inversa de B (si existe).

**Vectores:**  
u = [2, 3]  
v = [1, -1]  

1. Calcula el producto interno u·v y determina ortogonalidad.  
2. Calcula magnitudes y ángulo entre u y v.

**Derivadas:**  
σ(x) = 1 / (1 + exp(-x))  # Función sigmoide  

1. Calcula σ'(x) simbólicamente y simplifícala.  
2. Evalúa σ'(0) y σ'(1) y explica su interpretación.
"""

# Nombre del estudiante:
# Nombre: Patricio Quishpe


In [3]:
import numpy as np
import sympy as sp

In [4]:
A = np.array([[1, 1],
              [2, 3]])

B = np.array([[0, 2],
              [1, 1]])

# Operaciones básicas
suma = A + B
resta = A - B
producto = A @ B

# Traspuesta e inversa
traspuesta_A = A.T

# Verificar si B es invertible
det_B = np.linalg.det(B)
if det_B != 0:
    inversa_B = np.linalg.inv(B)
else:
    inversa_B = "No existe (determinante = 0)"

print("=== MATRICES ===")
print("A + B =\n", suma)
print("A - B =\n", resta)
print("A × B =\n", producto)
print("Traspuesta de A =\n", traspuesta_A)
print("Determinante de B =", det_B)
print("Inversa de B =\n", inversa_B)

=== MATRICES ===
A + B =
 [[1 3]
 [3 4]]
A - B =
 [[ 1 -1]
 [ 1  2]]
A × B =
 [[1 3]
 [3 7]]
Traspuesta de A =
 [[1 2]
 [1 3]]
Determinante de B = -2.0
Inversa de B =
 [[-0.5  1. ]
 [ 0.5  0. ]]


In [5]:
u = np.array([2, 3])
v = np.array([1, -1])

# Producto interno
producto_interno = np.dot(u, v)

# Determinar ortogonalidad
if producto_interno == 0:
    ortogonal = "Sí, son ortogonales"
else:
    ortogonal = "No, no son ortogonales"

# Magnitudes (normas)
magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)

# Ángulo entre u y v
cos_theta = producto_interno / (magnitud_u * magnitud_v)
angulo = np.degrees(np.arccos(cos_theta))

print("\n=== VECTORES ===")
print("u · v =", producto_interno)
print("¿Son ortogonales?", ortogonal)
print("|u| =", round(magnitud_u, 3))
print("|v| =", round(magnitud_v, 3))
print("Ángulo entre u y v =", round(angulo, 2), "grados")


=== VECTORES ===
u · v = -1
¿Son ortogonales? No, no son ortogonales
|u| = 3.606
|v| = 1.414
Ángulo entre u y v = 101.31 grados


In [6]:
x = sp.Symbol('x', real=True)
sigma = 1 / (1 + sp.exp(-x))  # Función sigmoide

# Derivada simbólica y simplificación
sigma_derivada = sp.diff(sigma, x)
sigma_derivada_simplificada = sp.simplify(sigma_derivada)

# Evaluación en puntos específicos
sigma_derivada_0 = sigma_derivada_simplificada.subs(x, 0)
sigma_derivada_1 = sigma_derivada_simplificada.subs(x, 1)

print("\n=== DERIVADAS ===")
print("σ(x) = 1 / (1 + e^(-x))")
print("σ'(x) =", sigma_derivada_simplificada)
print("σ'(0) =", float(sigma_derivada_0))
print("σ'(1) =", float(sigma_derivada_1))

# Interpretación:
print("\nInterpretación:")
print("La derivada σ'(x) = σ(x) * (1 - σ(x)) muestra la tasa de cambio de la sigmoide.")
print("En x = 0, la pendiente es máxima (~0.25), indicando alta sensibilidad.")
print("En x = 1, la pendiente disminuye (~0.196), mostrando saturación progresiva.")



=== DERIVADAS ===
σ(x) = 1 / (1 + e^(-x))
σ'(x) = 1/(4*cosh(x/2)**2)
σ'(0) = 0.25
σ'(1) = 0.19661193324148185

Interpretación:
La derivada σ'(x) = σ(x) * (1 - σ(x)) muestra la tasa de cambio de la sigmoide.
En x = 0, la pendiente es máxima (~0.25), indicando alta sensibilidad.
En x = 1, la pendiente disminuye (~0.196), mostrando saturación progresiva.
