## Ejercicio 3

**Matrices:**  
A = [[2, 1], [0, 3]]  
B = [[1, 2], [3, 0]]  

1. Calcula A + B y A × B.  
2. Calcula la inversa de A y el determinante de B.

**Vectores:**  
u = [1, 3]  
v = [-1, 2]  

1. Calcula el producto interno u·v.  
2. Calcula la magnitud de cada vector.

**Derivadas:**  
h(x) = sin(2*x**2 + 3*x)  

1. Calcula la derivada h'(x) usando regla de la cadena.  
2. Evalúa h'(1) y h'(0).


In [28]:
import numpy as np
import sympy as sp

#Matrices
A = np.array([[2, 1],[0,3]])
B = np.array([[1,2],[3,0]])

#Suma y multiplicacion de matrices
suma = A + B 
print("La suma de la matriz A y B es: \n", suma)
multiplicacion =np.dot(A,B)
print("La multiplicacion de la matriz A y B es: \n",multiplicacion)

#Inversa y determinante de la matrices
Inversa_A = np.linalg.inv(A)
print("La inversa de la matriz A es:\n ",Inversa_A)

Determinante_B = np.linalg.det(B)
print("La Determinante de la matriz B es:\n",Determinante_B)

#Vectores
u = np.array([1,3])
v= np.array([-1,2])

#Producto Interno
producto_int = np.dot(u,v)
print("El producto interno de u·v es:\n ",producto_int)
#Magnitud de cada vector
magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)
print("La magnitud del vector u es: \n",magnitud_u)
print("La magnitud del vector v es: \n",magnitud_v)

#Derivadas
x = sp.symbols('x')
h = sp.sin(2*x**2 + 3*x)

#Derivada de h(x)
h_derivada = sp.diff(h, x)
print("La derivada de h'(x) =", h_derivada)

#Evaluar la derivada
valor_derivada_1 = h_derivada.subs(x, 1)
print("El valor de la derivada evaluada en uno es: ",sp.N(valor_derivada_1))
valor_derivada_0 = h_derivada.subs(x, 0)
print("El valor de la derivada evaluada en cero es: ",sp.N(valor_derivada_0))

La suma de la matriz A y B es: 
 [[3 3]
 [3 3]]
La multiplicacion de la matriz A y B es: 
 [[5 4]
 [9 0]]
La inversa de la matriz A es:
  [[ 0.5        -0.16666667]
 [ 0.          0.33333333]]
La Determinante de la matriz B es:
 -6.0
El producto interno de u·v es:
  5
La magnitud del vector u es: 
 3.1622776601683795
La magnitud del vector v es: 
 2.23606797749979
La derivada de h'(x) = (4*x + 3)*cos(2*x**2 + 3*x)
El valor de la derivada evaluada en uno es:  1.98563529824258
El valor de la derivada evaluada en cero es:  3.00000000000000
