"""
# Práctica de Python – Ejercicios Combinados

📌 Instrucciones generales:

1. Cada estudiante debe elegir **uno** de los siguientes cinco ejercicios para resolver.  
2. No más de **11 estudiantes por ejercicio**.  
3. Deben escribir su **nombre completo** en la sección indicada debajo del ejercicio elegido.  
4. Todos los ejercicios se resuelven usando Python (NumPy y SymPy).  
5. Cada ejercicio incluye:
   - Operaciones con matrices
   - Operaciones con vectores
   - Derivadas (normales, parciales, de funciones compuestas o sigmoide)
"""

# ----------------------------------------------------------
# EJERCICIO 5
# ----------------------------------------------------------
"""
## Ejercicio 5

**Matrices:**  
A = [[1, 1], [2, 3]]  
B = [[0, 2], [1, 1]]  

1. Calcula A + B, A - B y A × B.  
2. Calcula la traspuesta de A y la inversa de B (si existe).

**Vectores:**  
u = [2, 3]  
v = [1, -1]  

1. Calcula el producto interno u·v y determina ortogonalidad.  
2. Calcula magnitudes y ángulo entre u y v.

**Derivadas:**  
σ(x) = 1 / (1 + exp(-x))  # Función sigmoide  

1. Calcula σ'(x) simbólicamente y simplifícala.  
2. Evalúa σ'(0) y σ'(1) y explica su interpretación.
"""


# Nombre del estudiante:
# Nombre: Aisha Gómez


In [5]:
import numpy as np
import sympy as sp

## Ejercicio 5

# Matrices

A = [[1, 1], [2, 3]]
B = [[0, 2], [1, 1]]
A = np.array(A)
B = np.array(B)

# Calcula A + B, A - B y A × B.

print("Suma de matrices (A + B):")
C = A + B
print(C)

print("Resta de matrices (A - B):")
D = A - B
print(D)

print("Producto matricial (A × B):")
E = np.dot(A, B)
print(E)


# Calcula la traspuesta de A y la inversa de B (si existe).

print("Traspuesta de A:")
A_tras = np.transpose(A)
print(A_tras)

print("Inversa de B (si existe):")
try:
    B_inv = np.linalg.inv(B)
    print(B_inv)
except np.linalg.LinAlgError:
    print("La matriz B no tiene inversa (es singular).")
# Vectores

u = [2, 3]
v = [1, -1]
u = np.array(u)
v = np.array(v)


# Calcula el producto interno u·v y determina ortogonalidad.

print("Producto interno u·v:")
prod_int = np.dot(u, v)
print(prod_int)

if prod_int == 0:
    print("Los vectores son ortogonales.")
else:
    print("Los vectores no son ortogonales.")

# Calcula magnitudes y ángulo entre u y v.

print("Magnitud de u:")
mag_u = np.linalg.norm(u)
print(mag_u)

print("Magnitud de v:")
mag_v = np.linalg.norm(v)
print(mag_v)

print("Ángulo entre u y v:")
ang = np.arccos(np.dot(u, v) / (mag_u * mag_v))
print(ang)

# σ(x) = 1 / (1 + exp(-x))  # Función sigmoide

X = sp.symbols('x')
sig = 1 / (1 + sp.exp(-X))
print("σ(x) =")
print(sig)

# Calcula σ'(x) simbólicamente y simplifícala.

print("Derivada simbólica σ'(x):")
dev = sp.diff(sig, X)
print(dev)

print("Derivada simplificada σ'(x):")
dev_simp = sp.simplify(dev)
print(dev_simp)

# Evalúa σ'(0) y σ'(1) y explica su interpretación.

print("Evaluación de σ'(x) en x = 0 y x = 1:")
sigmoide_0 = dev_simp.subs(X, 0)
sigmoide_1 = dev_simp.subs(X, 1)

print("σ'(0) =", sigmoide_0)
print("σ'(1) =", sigmoide_1)


# Interpretación:

# La derivada es máxima en x = 0, lo que significa que la función sigmoide cambia
# más rápido cerca del origen. Aquí la función es más sensible a cambios en X, mientras que
# si se aleja de 0, como en 1, la derivada disminuye, y eso muestra que la función comienza
# a saturarse y los cambios realizados en X no producen grandes cambios en Y.

Suma de matrices (A + B):
[[1 3]
 [3 4]]
Resta de matrices (A - B):
[[ 1 -1]
 [ 1  2]]
Producto matricial (A × B):
[[1 3]
 [3 7]]
Traspuesta de A:
[[1 2]
 [1 3]]
Inversa de B (si existe):
[[-0.5  1. ]
 [ 0.5  0. ]]
Producto interno u·v:
-1
Los vectores no son ortogonales.
Magnitud de u:
3.605551275463989
Magnitud de v:
1.4142135623730951
Ángulo entre u y v:
1.7681918866447774
σ(x) =
1/(1 + exp(-x))
Derivada simbólica σ'(x):
exp(-x)/(1 + exp(-x))**2
Derivada simplificada σ'(x):
1/(4*cosh(x/2)**2)
Evaluación de σ'(x) en x = 0 y x = 1:
σ'(0) = 1/4
σ'(1) = 1/(4*cosh(1/2)**2)
