"""

Ejercicio 5
Matrices:
A = [[1, 1], [2, 3]]
B = [[0, 2], [1, 1]]

Calcula A + B, A - B y A × B.
Calcula la traspuesta de A y la inversa de B (si existe).
Vectores:
u = [2, 3]
v = [1, -1]

Calcula el producto interno u·v y determina ortogonalidad.
Calcula magnitudes y ángulo entre u y v.
Derivadas:
σ(x) = 1 / (1 + exp(-x)) # Función sigmoide

Calcula σ'(x) simbólicamente y simplifícala.
Evalúa σ'(0) y σ'(1) y explica su interpretación. """

In [ ]:

import numpy as np

#Matrices:

A = [[1, 1], [2, 3]]
B = [[0, 2], [1, 1]]

MA = np.array(A)
MB = np.array(B)

#Calcula A + B, A - B y A × B.

suma = MA + MB
resta = MA - MB
multiplicacion = np.dot(MA, MB)

print("A + B =\n", suma)
print("\nA - B =\n", resta)
print("\nA x B =\n", multiplicacion)

#Calcula la traspuesta de A y la inversa de B (si existe).

transpuesta_A = MA.T

#Si B tiene inversa

det_B = np.linalg.det(MB)

if det_B != 0:
    inversa_B = np.linalg.inv(MB)
else:
    inversa_B = None

print("\nTraspuesta de A =\n", transpuesta_A)
print("\nDeterminante de B =", det_B)
if inversa_B is not None:
    print("\nInversa de B =\n", inversa_B)
else:
    print("\nB no tiene inversa (determinante = 0)")


A + B =
 [[1 3]
 [3 4]]

A - B =
 [[ 1 -1]
 [ 1  2]]

A x B =
 [[1 3]
 [3 7]]

Traspuesta de A =
 [[1 2]
 [1 3]]

Determinante de B = -2.0

Inversa de B =
 [[-0.5  1. ]
 [ 0.5  0. ]]


In [ ]:
#Vectores:

import math

u = [2, 3]
v = [1, -1]

#Calcula el producto interno u·v y determina ortogonalidad.

#producto interno u·v
produc_interno = u[0]*v[0] + u[1]*v[1]
print("Producto interno u·v =", produc_interno)

#ortogonalidad
if produc_interno == 0:
    print("Los vectores son ortogonales")
else:
    print("Los vectores no son ortogonales")

#Calcula magnitudes y ángulo entre u y v.

#magnitudes ||u||= raiz(2^2 + 3^2)
magnitud_u = math.sqrt(u[0]**2 + u[1]**2)
magnitud_v = math.sqrt(v[0]**2 + v[1]**2)

print("magnitudes de u =", magnitud_u)
print("magnitude de v =", magnitud_v)

# ángulo entre u y v
cos_theta = produc_interno / (magnitud_u * magnitud_v)
angulo = math.degrees(math.acos(cos_theta))

print("Ángulo entre u y v =", angulo, "grados")


Producto interno u·v = -1
Los vectores no son ortogonales
magnitudes de u = 3.605551275463989
magnitude de v = 1.4142135623730951
Ángulo entre u y v = 101.30993247402021 grados


In [3]:
#Derivadas:
#σ(x) = 1 / (1 + exp(-x)) # Función sigmoide

import sympy as sp

x = sp.Symbol('x')

#Calcula σ'(x) simbólicamente y simplifícala.

#función sigmoide σ(x)
sigma = 1 / (1 + sp.exp(-x))

# Derivar simbólicamente σ'(x)
sigma_derivada = sp.diff(sigma, x)

# Simplificada
sigma_derivada_simplificada = sp.simplify(sigma_derivada)

#Evalúa σ'(0) y σ'(1) y explica su interpretación.

# Evaluar σ'(0) y σ'(1)
valor_0 = sigma_derivada_simplificada.subs(x, 0).evalf()
valor_1 = sigma_derivada_simplificada.subs(x, 1).evalf()

print("σ(x) =", sigma)
print("σ'(x) =", sigma_derivada)
print("σ'(x) simplificada =", sigma_derivada_simplificada)
print("σ'(0) =", valor_0)
print("σ'(1) =", valor_1)



σ(x) = 1/(1 + exp(-x))
σ'(x) = exp(-x)/(1 + exp(-x))**2
σ'(x) simplificada = 1/(4*cosh(x/2)**2)
σ'(0) = 0.250000000000000
σ'(1) = 0.196611933241482
