"""
# Práctica de Python – Ejercicios Combinados

📌 Instrucciones generales:

1. Cada estudiante debe elegir **uno** de los siguientes cinco ejercicios para resolver.  
2. No más de **11 estudiantes por ejercicio**.  
3. Deben escribir su **nombre completo** en la sección indicada debajo del ejercicio elegido.  
4. Todos los ejercicios se resuelven usando Python (NumPy y SymPy).  
5. Cada ejercicio incluye:
   - Operaciones con matrices
   - Operaciones con vectores
   - Derivadas (normales, parciales, de funciones compuestas o sigmoide)
"""
# ----------------------------------------------------------
# EJERCICIO 3

## Ejercicio 3

**Matrices:**  
A = [[2, 1], [0, 3]]  
B = [[1, 2], [3, 0]]  

1. Calcula A + B y A × B.  
2. Calcula la inversa de A y el determinante de B.

**Vectores:**  
u = [1, 3]  
v = [-1, 2]  

1. Calcula el producto interno u·v.  
2. Calcula la magnitud de cada vector.

**Derivadas:**  
h(x) = sin(2*x**2 + 3*x)  

1. Calcula la derivada h'(x) usando regla de la cadena.  
2. Evalúa h'(1) y h'(0).
"""

# Nombre del estudiante:
# Nombre: 
Anthony Pachay



In [4]:
!pip install sympy
import numpy as np
import sympy as sp

print("--- Operaciones con Matrices ---")

A = np.array([[2, 1],
              [0, 3]])

B = np.array([[1, 2],
              [3, 0]])

print(f"Matriz A:\n{A}")
print(f"Matriz B:\n{B}\n")

suma_AB = A + B
print(f"Suma A + B:\n{suma_AB}\n")

producto_AB = A @ B  
print(f"Producto A x B:\n{producto_AB}\n")

try:
    inversa_A = np.linalg.inv(A)
    print(f"Inversa de A (A^-1):\n{inversa_A}\n")
except np.linalg.LinAlgError:
    print("La matriz A no tiene inversa (es singular).\n")

det_B = np.linalg.det(B)
print(f"Determinante de B: {det_B}\n")


print("--- Operaciones con Vectores ---")

u = np.array([1, 3])
v = np.array([-1, 2])

print(f"Vector u: {u}")
print(f"Vector v: {v}\n")

producto_interno_uv = np.dot(u, v) 
print(f"Producto interno u·v: {producto_interno_uv}\n")

magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)
print(f"Magnitud de u (||u||): {magnitud_u}")
print(f"Magnitud de v (||v||): {magnitud_v}\n")


print("--- Cálculo de Derivadas ---")

x = sp.symbols('x')
h = sp.sin(2*x**2 + 3*x)
print(f"Función h(x) = {h}\n")

h_prima = sp.diff(h, x)
print(f"Derivada h'(x) = {h_prima}\n")

valor_h_prima_1 = h_prima.subs(x, 1)
print(f"h'(1) = {valor_h_prima_1}")
print(f"Valor numérico de h'(1) ≈ {valor_h_prima_1.evalf()}\n") 


valor_h_prima_0 = h_prima.subs(x, 0)
print(f"h'(0) = {valor_h_prima_0}")
print(f"Valor numérico de h'(0) = {valor_h_prima_0.evalf()}\n") 

--- Operaciones con Matrices ---
Matriz A:
[[2 1]
 [0 3]]
Matriz B:
[[1 2]
 [3 0]]

Suma A + B:
[[3 3]
 [3 3]]

Producto A x B:
[[5 4]
 [9 0]]

Inversa de A (A^-1):
[[ 0.5        -0.16666667]
 [ 0.          0.33333333]]

Determinante de B: -6.0

--- Operaciones con Vectores ---
Vector u: [1 3]
Vector v: [-1  2]

Producto interno u·v: 5

Magnitud de u (||u||): 3.1622776601683795
Magnitud de v (||v||): 2.23606797749979

--- Cálculo de Derivadas ---
Función h(x) = sin(2*x**2 + 3*x)

Derivada h'(x) = (4*x + 3)*cos(2*x**2 + 3*x)

h'(1) = 7*cos(5)
Valor numérico de h'(1) ≈ 1.98563529824258

h'(0) = 3
Valor numérico de h'(0) = 3.00000000000000

