In [2]:
#EJERCICIO 5 TRABAJO
import numpy as np
m_A = np.array([[1,1],[2,3]])
m_B= np.array([[0,2],[1,1]])

#1. Calculo de suma, multiplicacion y resta de matrices

print("La suma de las matrices A y B son:\n",m_A+m_B)

print("\nLa resta de las matrices A y B es:\n", m_A - m_B)

print("\nLa resta de las matrices A y B es:\n", m_A @ m_B)

#Transpuesta y matriz inversa de B

print("\nLa transpuesta de A es:\n", m_A.T)

if np.linalg.det(m_B) !=0:
    inversa = np.linalg.inv(m_B)
    print("\nLa matriz inversa de B es:\n", inversa)
else:
    print("La matriz B no tiene inversa")


#vectores
import math

u = np.array([2,3])
v = np.array([1,-1])

producto_interno = u @ v
print("\nEl producto interno entre u y v es: ",producto_interno)

magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)

print("La magnitud de u es:", round(magnitud_u, 2))
print("La magnitud de v es:", round(magnitud_v, 2))

angulo = math.acos(np.dot(u,v)/(magnitud_u*magnitud_v))

print("El ángulo entre los vectores u y v es:", round(math.degrees(angulo),2))

#Derivadas
import sympy as sp

x = sp.symbols('x')
sigma = 1/(1 + sp.exp(-x))

df = sp.diff(sigma, x)

print("\nLa derivada de σ es: \n",df)
print("\nLa forma simplificada es: \n", sp.simplify(df))

df_0 = df.subs(x, 0)
df_1 = df.subs(x, 1)

print("\nσ'(0) =", round(df_0.evalf(),2))
print("\nσ'(1) =", round(df_1.evalf(),2))






La suma de las matrices A y B son:
 [[1 3]
 [3 4]]

La resta de las matrices A y B es:
 [[ 1 -1]
 [ 1  2]]

La resta de las matrices A y B es:
 [[1 3]
 [3 7]]

La transpuesta de A es:
 [[1 2]
 [1 3]]

La matriz inversa de B es:
 [[-0.5  1. ]
 [ 0.5  0. ]]

El producto interno entre u y v es:  -1
La magnitud de u es: 3.61
La magnitud de v es: 1.41
El ángulo entre los vectores u y v es: 101.31

La derivada de σ es: 
 exp(-x)/(1 + exp(-x))**2

La forma simplificada es: 
 1/(4*cosh(x/2)**2)

σ'(0) = 0.25

σ'(1) = 0.20
